# -*- coding: utf-8 -*-
"""rotas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/102RRdmd339sca18oVcpA16Gup1JSIiLX
"""

pip install osmnx

import osmnx as ox

# Baixe a rede de ruas para todo o Sumé
place = "Sumé, Brazil"
G_DF = ox.graph.graph_from_place(place, network_type='drive', simplify=False, retain_all=False, truncate_by_edge=False, which_result=None, custom_filter=None)

# Salve a rede para um arquivo .graphml
ox.save_graphml(G_DF, filepath="sume.graphml")

# Carregar a rede leve
G = ox.load_graphml("sume.graphml")

# Plotar o mapa
ox.plot_graph(G)

"""# OUTRA PARTE"""

import networkx as nx
from geopy.distance import geodesic
import matplotlib.pyplot as plt
import folium
import pickle

import networkx as nx
from geopy.distance import geodesic
import folium

#import networkx as nx
import folium
from geopy.distance import geodesic

# ==================== 1. DADOS E CONFIGURAÇÕES ====================
CAPITAIS = {
    # SUL
    0: ("Porto Alegre", -30.0346, -51.2177),
    1: ("Florianópolis", -27.5954, -48.5480),
    2: ("Curitiba", -25.4244, -49.2654),

    # SUDESTE
    3: ("São Paulo", -23.5505, -46.6333),
    4: ("Rio de Janeiro", -22.9083, -43.1964),
    5: ("Belo Horizonte", -19.9167, -43.9345),
    6: ("Vitória", -20.2976, -40.2958),

    # CENTRO-OESTE
    7: ("Brasília", -15.7942, -47.8822),
    8: ("Goiânia", -16.6869, -49.2648),
    9: ("Campo Grande", -20.4428, -54.6460),
    10: ("Cuiabá", -15.6014, -56.0979),

    # NORDESTE
    11: ("Salvador", -12.9714, -38.5014),
    12: ("Aracaju", -10.9472, -37.0731),
    13: ("Maceió", -9.6498, -35.7089),
    14: ("Recife", -8.0476, -34.8768),
    15: ("João Pessoa", -7.1150, -34.8631),
    16: ("Natal", -5.7936, -35.1986),
    17: ("Fortaleza", -3.7172, -38.5433),
    18: ("Teresina", -5.0892, -42.8040),
    19: ("São Luís", -2.5307, -44.3068),

    # NORTE
    20: ("Belém", -1.4558, -48.4902),
    21: ("Macapá", 0.0356, -51.0705),
    22: ("Manaus", -3.1189, -60.0212),
    23: ("Porto Velho", -8.7618, -63.9004),
    24: ("Boa Vista", 2.8197, -60.6714),
    25: ("Palmas", -10.2129, -48.3603),
    26: ("Rio Branco", -9.9754, -67.8076),
}

COORDS = {i: (lat, lon) for i, (_, lat, lon) in CAPITAIS.items()}

REGIOES = {
    'SUL': [0, 1, 2],
    'SUDESTE': [3, 4, 5, 6],
    'CENTRO_OESTE': [7, 8, 9, 10],
    'NORDESTE': [11, 12, 13, 14, 15, 16, 17, 18, 19],
    'NORTE': [20, 21, 22, 23, 24, 25, 26]
}

CORES_REGIOES = {
    'SUL': 'blue', 'SUDESTE': 'red', 'CENTRO_OESTE': 'green',
    'NORDESTE': 'orange', 'NORTE': 'purple'
}

# ==================== 2. FUNÇÕES DO GRAFO ====================
def _gerar_conexoes_intra_regiao(grafo, regioes, coords):
    for _, ids in regioes.items():
        for i in ids:
            for j in ids:
                if i != j:
                    dist = geodesic(coords[i], coords[j]).km
                    if dist < 1500:
                        grafo.add_edge(i, j, weight=round(dist, 1), tipo='intra')

def _gerar_conexoes_entre_regioes(grafo, regioes, coords):
    portas_saida = {
        'SUL': 0, 'SUDESTE': 3, 'CENTRO_OESTE': 7,
        'NORDESTE': 11, 'NORTE': 20
    }
    lista_regioes_keys = list(regioes.keys())

    for origem_reg, porta in portas_saida.items():
        idx_atual = lista_regioes_keys.index(origem_reg)
        destino_reg = lista_regioes_keys[(idx_atual + 1) % len(lista_regioes_keys)]
        destinos_possiveis = regioes[destino_reg]

        distancias = []
        for dest in destinos_possiveis:
            dist = geodesic(coords[porta], coords[dest]).km
            distancias.append((dest, dist))

        destino_mais_prox, dist_final = min(distancias, key=lambda x: x[1])
        grafo.add_edge(porta, destino_mais_prox, weight=round(dist_final, 1), tipo='inter')

def criar_grafo_capitais(capitais, regioes, coords):
    G = nx.DiGraph()
    for idx, (nome, lat, lon) in capitais.items():
        G.add_node(idx, pos=(lat, lon), nome=nome, regiao=None)
    for regiao, ids in regioes.items():
        for idx in ids:
            G.nodes[idx]['regiao'] = regiao
    _gerar_conexoes_intra_regiao(G, regioes, coords)
    _gerar_conexoes_entre_regioes(G, regioes, coords)
    return G

# ==================== 3. FUNÇÕES DE ANÁLISE ====================
def imprimir_estatisticas(G, regioes):
    print("=== ANÁLISE DO GRAFO ===")
    print(f"Capitais: {G.number_of_nodes()}")
    print(f"Rotas intra-região: {sum(1 for _, _, d in G.edges(data=True) if d.get('tipo') == 'intra')}")
    print(f"Rotas inter-região: {sum(1 for _, _, d in G.edges(data=True) if d.get('tipo') == 'inter')}")
    print(f"Total de rotas: {G.number_of_edges()}")
    print()
    for reg, ids in regioes.items():
        grau = sum(G.out_degree(n) for n in ids)
        print(f"{reg}: {len(ids)} capitais, {grau} rotas saindo")

def calcular_rota_dijkstra(G, origem, destino):
    caminho = nx.dijkstra_path(G, origem, destino)
    distancia = nx.dijkstra_path_length(G, origem, destino)
    return caminho, distancia

# ==================== 4. FUNÇÃO DE RENDERIZAÇÃO ====================
def desenhar_mapa(G, caminho, distancia, origem, destino):
    mapa = folium.Map(location=[-14.2350, -51.9253], zoom_start=4)

    # Nós
    for node, data in G.nodes(data=True):
        cor = CORES_REGIOES[data['regiao']]
        folium.CircleMarker(
            location=data['pos'], radius=8, color=cor,
            fill=True, fillColor=cor, fillOpacity=0.7,
            popup=f"<b>{data['nome']}</b><br>Região: {data['regiao']}"
        ).add_to(mapa)

    # Arestas Intra (finas e coloridas)
    for u, v, data in G.edges(data=True):
        if data.get('tipo') == 'intra':
            cor = CORES_REGIOES[G.nodes[u]['regiao']]
            folium.PolyLine([G.nodes[u]['pos'], G.nodes[v]['pos']], color=cor, weight=2, opacity=0.6).add_to(mapa)

    # Arestas Inter (grossas e pretas)
    for u, v, data in G.edges(data=True):
        if data.get('tipo') == 'inter':
            folium.PolyLine([G.nodes[u]['pos'], G.nodes[v]['pos']], color='black', weight=5, opacity=0.9).add_to(mapa)

    # Caminho Ótimo (vermelho)
    caminho_coords = [G.nodes[n]['pos'] for n in caminho]
    folium.PolyLine(caminho_coords, color='red', weight=8, opacity=1, popup=f"Distância: {distancia:,.0f} km").add_to(mapa)

    # Marcadores Início/Fim
    folium.Marker(G.nodes[origem]['pos'], popup="INÍCIO", icon=folium.Icon(color='green', icon='play')).add_to(mapa)
    folium.Marker(G.nodes[destino]['pos'], popup="FIM", icon=folium.Icon(color='red', icon='stop')).add_to(mapa)

    return mapa

def escolher_ids():
  print("\n--- LISTA DE CAPITAIS ---")
  for cid, (nome, _, _) in CAPITAIS.items():
      print(f"[{cid}] {nome}")
  print("-" * 25)

  origem = int(input("Digite o ID da ORIGEM: "))
  destino = int(input("Digite o ID do DESTINO: "))

  return origem, destino

# ==================== 5. MAIN ====================
def main():
    # 1. Criar o Grafo
    G_capitais = criar_grafo_capitais(CAPITAIS, REGIOES, COORDS)

    # 2. Analisar Estatísticas
    imprimir_estatisticas(G_capitais, REGIOES)

    # 3. Escolher Origem e Destino (Input do usuário)
    origem, destino = escolher_ids()

    # 4. Calcular Rota
    caminho, distancia = calcular_rota_dijkstra(G_capitais, origem, destino)

    print(f"\n=== CAMINHO ÓTIMO (DIJKSTRA) ===")
    print(f"De: {CAPITAIS[origem][0]}")
    print(f"Para: {CAPITAIS[destino][0]}")
    print(" -> ".join([CAPITAIS[n][0] for n in caminho]))
    print(f"Distância: {distancia:,.0f} km")
    print(f"Trechos: {len(caminho)-1}")

    # 5. Gerar e Salvar Mapa
    mapa = desenhar_mapa(G_capitais, caminho, distancia, origem, destino)

    arquivo_saida = "mapa_capitais.html"
    mapa.save(arquivo_saida)
    print(f"\nMapa gerado com sucesso: {arquivo_saida}")

if __name__ == "__main__":
    main()


"""# distâncias considerando o trajeto das rodovias"""

import osmnx as ox
import networkx as nx
from geopy.distance import geodesic
import folium

# ==================== 1. PONTOS REAIS DE CAMPINA GRANDE ====================
pontos = {
    "Açude Velho": (-7.2294, -35.8819),
    "Parque do Povo": (-7.2306, -35.8811),
    "UFCG Campina Grande": (-7.2137, -35.9071)
}

# ==================== 2. BAIXAR GRAFO REAL ====================
print("Baixando grafo real de Campina Grande...")
G = ox.graph_from_place("Campina Grande, Paraíba, Brazil", network_type="drive")

# ==================== 3. FUNÇÕES AUXILIARES ====================
def heuristica(n1, n2):
    """Distância geodésica em km (heurística A*)"""
    return geodesic(
        (G.nodes[n1]['y'], G.nodes[n1]['x']),
        (G.nodes[n2]['y'], G.nodes[n2]['x'])
    ).km

def mais_proximo(G, coord):
    """Encontra o nó mais próximo das coordenadas (lat, lon)"""
    return ox.distance.nearest_nodes(G, coord[1], coord[0])

def caminho_entre(G, origem_nome, destino_nome):
    """Calcula o caminho ótimo entre dois pontos"""
    o_lat, o_lon = pontos[origem_nome]
    d_lat, d_lon = pontos[destino_nome]

    origem = mais_proximo(G, (o_lat, o_lon))
    destino = mais_proximo(G, (d_lat, d_lon))

    caminho = nx.astar_path(G, origem, destino, heuristic=heuristica, weight='length')

    distancia = sum(G[u][v][0]['length'] for u, v in zip(caminho[:-1], caminho[1:])) / 1000
    return caminho, distancia, origem, destino

# ==================== 4. DEFINIR ORIGEM/DESTINO ====================
origem_nome = "Parque do Povo"
destino_nome = "UFCG Campina Grande"

print(f"\nCalculando menor rota entre {origem_nome} e {destino_nome}...")
caminho, distancia, origem, destino = caminho_entre(G, origem_nome, destino_nome)
print(f"Distância total: {distancia:,.2f} km")

# ==================== 5. CRIAR MAPA INTERATIVO ====================
print("Gerando mapa interativo...")

coords = [(G.nodes[n]['y'], G.nodes[n]['x']) for n in caminho]
mapa = folium.Map(location=[-7.24, -35.89], zoom_start=14)

# Adicionar rota
folium.PolyLine(
    coords,
    color='red',
    weight=6,
    opacity=0.8,
    popup=f"Rota ótima ({distancia:,.2f} km)"
).add_to(mapa)

# Adicionar marcadores
for nome, (lat, lon) in pontos.items():
    cor = (
        'green' if nome == origem_nome
        else 'red' if nome == destino_nome
        else 'blue'
    )
    folium.Marker(
        location=(lat, lon),
        popup=f"<b>{nome}</b>",
        icon=folium.Icon(color=cor)
    ).add_to(mapa)

# Salvar mapa
mapa.save("rota_campina.html")
print("\nMapa salvo como 'rota_campina.html'")

mapa